### ISSUE TITLE
Merging existing SEPAL documentation with sepal-doc

### ISSUE THREAD

**Issue by eriklindquist** [openforis/sepal-doc#4]
How do we merge existing documentation with this repo? Can we do that with what SIG has prepared?

**Comment by 12rambau** [comment]
I was reading their documentation (I assume you're talking about this one https://github.com/sig-gis/SEPAL-CEO) this very morning and I was writing an email to Karis. 

2 options:

1/ they want to keep an independant documentation and I then need to retreive the files from their documentation (as I do for modules here  https://github.com/openforis/sepal-doc/blob/fde70ca135b98d2e889096a3b3fab987c95ba033/docs/source/conf.py#L80
2/ they don't want to keep it and I can simply copy/paste the rst files they created as they we are both using readthedoc

**Comment by 12rambau** [comment]
I think tomorrow I'll be in documentation mood. If it's alright with everyone, I'll do the easiest solution for me which is : 
- hard copy and restructuration of the SIG-GIS documentation (to fit in the repository hierarchy)
- disclaimer **at the beginning** to give full credit to SIG-GIS on this very documentation page
- SIG-GIS, you'll stay master in your castle and decide either you prefer to keep the doc active or to continue working here

**Comment by 12rambau** [comment]
I've just finish merging the full SEPAL-CEO documentation in the sepal-doc repository. 

## Structural modifications

- the sepal-doc repository uses a different sphinx template. Each documentation lives in the cookbook `toctree` so all the modules have been gathered in 1 single page. I needed to rearrange the hierarchy to reflect this change.
- I used `Graphviz` extension to create flowcharts instead of screenshots. it will be easier to modify directly in the code 
- There were "|" character after all `image`, I assume it was to increase the padding. Very bad habit as it's printed in the PDF version (that use LateX). Instead, I've used the `figure` directive that add padding at the end of the images. 
- the documentation was a full bullet point document with numbering at each line. I assumed that no-one will refer to line `1.1.12.a.6.c.2`. Instead, I've regrouped what seems to work together in unnumbered paragraphs.
- the markdown style table are not easy not modify (line breaks are a pain). I replaced them all with the `table-csv` directive
- I removed all the numbering from the titles. This numbering can be automatically generated by using `:numbered:` option in the `toctree`. It avoids the duplication of the numeration when exporting to PDF. 
- The 2 only admonitions were `note` and `warning` I reintroduce all the coloured panel with `seealso`, `warning`, `tip`, `danger`

## Remaining issues 

- [ ] I don't like the numbering way. it starts with the documentation tree and not the page tree. In need to better understand how it works
- [ ] some reshaping is required on some tables and images
- [ ] need to create a `br` custom directive (in raw html) to use in all the documentation

**Comment by kdyson** [comment]
Hi @12rambau , I've fixed a few typos in the SIG repo copy of this.

Let me know what process for this and future updates you want to use. I see you needed to make some modifications (the pipes were because images & following indented sub-list text were _not_ behaving nicely...). 

Thanks!

**Comment by 12rambau** [comment]
The bot is perfectly unrelevant at the moment, it open wrong PR and I'm currently working in the all-contributor repository to make it compatible with .rst format. 

If you want to make modifications to this repository you can simply use the edit btn of the Github interface. It will automatically create a patch branch and open a PR for you. you can also use the edit button from the website directly (right side of the window under the table of content) it will lead you to the appropriate file.

If we want to keep both your and our repository I'm listening to yours so I will be able to copy-paste modifications.

**Comment by 12rambau** [comment]
I'm now introducing recipes within the SEPAL documentation and I'm starting to have second thoughts... 

Is it making sense to have the openMRV documenation duplicated (not wired, duplicated) here ? 

My point is: 
- For maintainers it doubles the work as any modification in openMRV will require modification here (or one of us is going down into the darkness of deprecation) 
- it is not core functionality of SEPAL but a way to use it, not sure it's meant to be in a software documentation 
- it's already published on a stable platform: http://www.openmrv.org/fr/-/modules/mrv/modules_1/image-mosaic-composite-creation-for-landsat-and-sentinel-2-in-google-earth-engine

**Comment by 12rambau** [comment]
note that to avoid cofusion with the rest of the recipes, workflows have their dedicated section since https://github.com/openforis/sepal-doc/commit/311e0f6873506a655b5bcadcc49f551ce4a07048

**Comment by 12rambau** [comment]
it's been a while since no modifications have been made to this side of the doc so I'll close this issue for now. feel free to reopen if needed or open another one for more specific modifications.
